server:
  port: ${PORT:8080}

app:
  frontend:
    url: ${FRONTEND_URL:https://edumart-web-frontend.onrender.com}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Dynamic service discovery allows us to use service names (lb://)
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:https://edumart-auth-service.onrender.com}
          predicates:
            - Path=/api/auth/**
        - id: student-service
          uri: ${STUDENT_SERVICE_URL:https://edumart-student-service.onrender.com}
          predicates:
            - Path=/api/student/**
        - id: course-service
          uri: ${COURSE_SERVICE_URL:lb://course-service}
          predicates:
            - Path=/api/courses/**

# Eureka Configuration - Pointing to your Discovery Server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Management Configuration - Unlocks the Actuator API
management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,routes"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always